sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        ic5V+MmExsj5iC27WxjO+kcH20RWodtkNTlTKhF3qzw4IHOysc+apilvwG+q8I2h2JviL7nEl+V6la8p75yy3jUrWnNDMpNWXLWmNZE2jOTU2y1d7T08a9x3bzT0ki2TncPY79Esi8oXnz9qmcWc3GhKthUlZ/n90LetlPRNjmLgTQ0UfPE5EsnJHU3uPwd7vBjv+nhei/m2+78g2W9GDyvnLmhpMhKAe96sJsu/5MG54kXz9IyCEr9GjAGD4OCUEM+NMq+74H+xDbqBvi0jHc2pijLJWhXIiZSX+edtwsWUm0WcGCB98Mld9TXmiHDI8MPNPcgRGpLj4G6lsdXfxAArsmK1H5wjDiKNlPPxsSYfU0L59803l4WOlDcb+59eRM/4hOEa3oN1mfLohOArx2+0oeMOq9H1yG1ximHy7FQXSxrOA1vdMbX9Zpu/jtWvgSIYsVh/dB50NlDyXc5IJf8AHYTxqGAh3Us58IbWcjUQEFWzKC9tQiGPSbZjsMfNEbvOHxC64pk3uYi3ztTq/0tyX0Dw2dVnghir1fX/KT41N0x6X2LPki5exvu+bOLN3ZFwkrXXDXrV1b69EPYUaAyYyxzkQksSYxVllyfjXF5ajCnRU8iVSCJRvYCm59ctzZXPF22UBimMMzgmB4KjUPSasQsgif3bC4tn7H+sO2U=
    - secure: >-
        iyw/O1Cju7elQETiBlmSQJ4ES2VdJ9yeS9atPXLy0xNvX825v8KiJMdfieYtewq1KSAvRE/zkTHbSvWlsVjQDJhLxxCz9bgEji3muPuhl2r2Z+nb6gYNPEQo9QF+Re8MPTkeI1ZGrn/dtoNlT7pEgxEDznMlEXGv32tYyLSf6CCT/irSQtgcWkZf24tPdLXTigwBXR0vTakA736Ts26rXCqCcvtstNfUYvAdoZn1DqyorqgzXdxZGeXsGoWatG3gc9OZfNAIEjYoJ09FryrQWNQSVAJchM0YKFOrz4TCJr0vea51LWOFLqzt+pPbBMJNfwCapEDwv5lDByEDUW8VPLGYb4u6fJimLKg8jHaaqYhmGaqLlal0qkTsgn84lKErdCv8Gsaicukn7qKMLyCEFqB193oafMdD/LGbheOE4/17MmH43bavHJJSu3NMHBJa4f/NmeUeTk76cisI5yYhR9273i4dGh+vd0oXWQQeaReAsXd/Cok7sVVnzX5e4P3kVQ99ka9lOZPukzsUQI+tmy5WHBKmnWXbzwJuB+fzBa8cHcrPhZH3AzG9KRcBKEG+dLULr04cZMNfHX0Sf7Ki8Bx2HUO2TklFaODkMiRhYup6CoQtcwzaoewOVqmqeYOuuXjQQ8lb7SPYRdkDuz6N0USW7FXYu4Gn96FisG2wABw=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
